version: '3'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "7027:5257" 
    networks:
      - shortenerurl-network
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - shortenerurl-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ShortenerUrl
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d # Mount the entire scripts folder
    networks:
      - shortenerurl-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - shortenerurl-network

networks:
  shortenerurl-network:
    driver: bridge

volumes:
  postgres_data: